### ISSUE TITLE
The format of '/data/wikiart/style_train.csv'

### ISSUE THREAD

**Issue by Tini00** [bcmi/PHDiffusion-Painterly-Image-Harmonization#6]
Your research is very interesting. I like this research very much. I have a problem. During the training of "python -m torch.distributed.launch --nproc_per_node 2 train.py", I found an error: "/data/wikiart/style_train.csv" does not exist. I would like to ask what this file is used for. What is its storage format?
Looking forward to your reply.Thanks

**Comment by pokaaa** [comment]
The file saves the selected images for training, together with its style category(27 in total). We have updated the repository and added this file for your reference. You can download it through this [link](https://github.com/bcmi/PHDiffusion-Painterly-Image-Harmonization/blob/main/style_train.csv).
